services:
  new-api:
    build: ./new-recruitment-api
    ports:
      - "3000:3000"
    volumes:
      - ./new-recruitment-api/database.sqlite:/app/database.sqlite
    depends_on:
      - legacy-api
    environment:
      NODE_ENV: production

  legacy-api:
    build: ./legacy-api
    ports:
      - "4040:4040"
